M48
; DRILL file {KiCad 7.0.8} date Mon Nov  6 13:51:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T13:51:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.687Y-4.273
X3.687Y-4.373
X3.687Y-4.473
T2
X3.2754Y-3.0369
X3.2754Y-5.033
X8.2439Y-3.3243
X8.2439Y-4.9464
T0
M30
